-- Migration number: 0007 	 2025-04-19T09:13:45.703Z
CREATE TABLE otps (
  otpId INTEGER PRIMARY KEY AUTOINCREMENT,
  partnerId TEXT NOT NULL,
  tableId TEXT NOT NULL,
  phoneNumber TEXT NOT NULL,
  otp TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiresAt DATETIME NOT NULL,
  is_used BOOLEAN DEFAULT 0
);